//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace genericPharmaWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int ID { get; set; }
        public string NI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public string Cedula { get; set; }
        public int IdCargo { get; set; }
        public int IdUsuario { get; set; }
        public int IdBodega { get; set; }
        public bool activo { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
